apiVersion: 1

datasources:
  - name: DB-Umami
    type: postgres
    access: proxy
    url: umami_db:5432
    user: umami
    secureJsonData:
      password: $__env{UMAMI_DB_PASSWORD}
    jsonData:
      database: umami
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
